<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>test2</name>
   <tag></tag>
   <elementGuidId>d04d0e7b-167d-4af3-ad3e-16512134c8af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>test</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
