<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sample2</name>
   <tag></tag>
   <elementGuidId>433310a4-fea5-45c1-a7b4-c46013544d98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>sample3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
