<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sample</name>
   <tag></tag>
   <elementGuidId>46eafd92-959e-449e-bd24-7c794ea26946</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>new</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
