<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sample4</name>
   <tag></tag>
   <elementGuidId>5a98975f-81ab-44ba-af45-511b2d06e481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>new</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
